#!/bin/sh
if [[ -a "$1" ]]; then
	data_file="$1"
else
	data_file="data/data.root"
fi

if [[ -a src/algorithm/example/tmvaClassificationApplication.cpp ]]; then
	root -l src/algorithm/example/tmvaClassificationApplication.cpp'("'"$data_file"'")'
else
	echo 'Error: no classification application script found'
fi

